version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: wee-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  mongodb:
    image: mongo:8.0.8
    container_name: wee-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: wee
    command: mongod --auth

  redis:
    image: redis/redis-stack-server:7.4.0-v3
    container_name: wee-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: